# Site settings
title: TechTrek
header-img: img/home-bg.png
email: n.daniele@gmail.com
copyright_name: ndaniele
description: > # this means to ignore newlines until "baseurl:"
  A Record Of Life Lessons Learned Through Coding! 
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: fuzzystarfilms
github_username:  ndaniele
learn_profile: ndaniele
email_username: n.daniele@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
